### ISSUE TITLE
IReadOnlyCollection<T> isn't selected

### ISSUE THREAD

**Issue by mgw854** [rvhuang/dotnet-ciig#1]
Given four questions, all of which I answered in the negative:

- I need to modify the collection.
- The original order of items is very important to me. 
- I want to retrieve item one-by-one before whole collection is ready. 
- The data have to be in one-to-many relationship. 

The resulting collection type was `IReadOnlyDictionary<TKey,TValue>`. I would have presumed the answer was `IReadOnlyCollection<T>`. Looking at the list of interfaces supported, it appears I'm missing a question about whether I need a key-value form or not.

**Comment by rvhuang** [comment]
> The original order of items is very important to me.

It seems like the issue is here. Most collections (such as `List<T>` and array) that implement `IReadOnlyCollection(T)` do keep the original order, but some of them don't (such as `HashSet<T>`). Hence there is a gray area about the item order of the interface. 

The question needs to be redesigned. Only interfaces such as `ISet<T>`, `IDictionary<TKey, TValue>`, `IReadOnlyDictionary<TKey, TValue>`, the original order of items are explicitly not guaranteed because of their purpose.

**Comment by rvhuang** [comment]
The question has been revamped. When the question gets the answer **Yes**, `IList<T>`, `IReadOnlyList<T>` and `IEnumerable<IGrouping<TKey, TElement>>` will be selected from the pool because there are the only three interfaces that guarantee item order. The former two are chosen because they support index. The latter one is because of that grouping operation won't change the original order of `IEnumerable<T>`.

**Comment by mgw854** [comment]
I would quibble that `IEnumerable<IGrouping<TKey, TElement>>` is no different than `IEnumerable<T>`, and therefore doesn't guarantee order. As for `IReadOnlyCollection<T>`, I did confirm that I could get it to show up in the UI by answering questions that included whether I cared about order.

**Comment by rvhuang** [comment]
> I would quibble that IEnumerable<IGrouping<TKey, TElement>> is no different than IEnumerable<T>

Hmm...this is correct as well. Let's remove it.
